channels:
  # - "https://www.youtube.com/@Reddit-rina/shorts"
  # - "https://www.youtube.com/@storiesclock/shorts"
  # - "https://www.youtube.com/@Reddit0World/shorts"
  # - "https://www.youtube.com/@RedditBook/shorts"
  # - "https://www.youtube.com/@storynest-l5q/shorts"
  # - "https://www.youtube.com/@redditdramatale/videos"
  # - "https://www.youtube.com/@redditdramatale/videos"
  # - "https://www.youtube.com/channel/UCYNDl_kj9H7Qx6W6kkGxrmQ"
  # - "https://www.youtube.com/@FamiliaReddit"
  # - "https://www.youtube.com/@couple_stories_prod/videos"
  # - "https://www.youtube.com/@RedditFamilyTales/videos"
  # - "https://www.youtube.com/@MineQley/videos"
  # - "https://www.youtube.com/@Narrativ01/videos"
  # - "https://www.youtube.com/@MainTalks095/videos"
  - https://www.youtube.com/@Reddit_Report/shorts

top_videos:
  count: 80
  sort_by: "view_count"     # view_count | like_count | upload_date | duration
  min_view_count: 100000
  include_shorts: true
  min_duration_seconds: 50    # 0 = no minimum
  max_duration_seconds: 7200
  flat_extract: true

subtitles:
  languages: ["en"]
  prefer_manual: false
  download_auto: true
  format: "vtt"

audio:
  enabled: false
  format: "mp3"                       # mp3 | wav | m4a | opus
  quality: "192"                      # bitrate in kbps (e.g. 128, 192, 320)

output:
  base_dir: "./out"
  shorts_subdir: "shorts"
  regular_subdir: "regular"
  filename_template: "%(channel)s/%(title)s [%(id)s]/%(title)s [%(id)s].%(ext)s"

runtime:
  concurrency: 30
  retries: 3
  verbose: false